# -*- coding: utf-8 -*-
"""type_casting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CppvLleyyBJ-pvUTIVxUzWWjKueV5BzG
"""



""" # type-casting
 types- implicit,explicit

```
# This is formatted as code
```


"""

a=10
print(type(a))
a="10"
print(type(a))
b=2.5
print(type(b))
c=True
print(type(c))

a=10
b="10"
print(a+b)

a=10.0
b=2.5
print(a+b)

a=10
b="10"
b=int(b)
print(a+b)

a=15
b="A"
b=int(b)
print(a+b)

a=10
b="5.5"
# b=float(b)
b=int(b)
print(b)

a="10"
a=int(a)
print(a,type(a))

a=float(a)
print(a,type(a))

a=bool(a)
print(a,type(a))

a=10
b=str(a)
print(b,type(b))



"""# ***swapping***"""

a=10
b=20
temp=a
a=b
b=temp
print(a,b)

a=10
b=15
a,b=b,a
print(a,b)

a=12.6
a=int(a)
print(a)

a=input("enter the name of student :")
b=input("enter fathers name :")
c=input("enter the class :")
d=int(input("enter roll_number :"))
print("student name :",a)
print("fathers name :",b)
print("class :",c)
print("roll number :",d)